---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/bosh2
    tag: latest

inputs:
  - name: bosh-repave-repo

run:
  path: bosh-repave-repo/ci/tasks/repave/task.sh

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  DEPLOYMENTS:
