jobs:
- name: repave
  serial: true
  plan:
  - get: bosh-repave-repo
    trigger: false
  - get: scheduler
    trigger: true
  - task: repave
    file: bosh-repave-repo/ci/tasks/repave/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}
      DEPLOYMENTS: {{deployments}}
      REPAVE_SINGLETON_JOBS: {{repave-singleton-jobs}}
      PERFORM_DRY_RUN_ONLY: {{perform-dry-run-only}}

resources:
- name: bosh-repave-repo
  type: git
  source:
    uri: https://github.com/pivotalservices/bosh-repave.git
    branch: master
- name: scheduler
  type: time
  source:
    start: {{scheduler-time-window-start}}
    stop: {{scheduler-time-window-stop}}
    location: {{scheduler-time-location}}
    days: [{{scheduler-days-to-run}}]
